2025-08-29 09:15:26,538 - INFO - Application starting...
2025-08-29 09:15:26,880 - DEBUG - Starting new HTTPS connection (1): api.telegra.ph:443
2025-08-29 09:15:27,685 - DEBUG - https://api.telegra.ph:443 "POST /createAccount/ HTTP/1.1" 200 214
2025-08-29 09:15:28,642 - DEBUG - Not in REPL -> leaving logger event level as is.
2025-08-29 09:15:28,646 - DEBUG - Looking for locale `en_US` in provider `faker.providers.address`.
2025-08-29 09:15:28,649 - DEBUG - Provider `faker.providers.address` has been localized to `en_US`.
2025-08-29 09:15:28,651 - DEBUG - Looking for locale `en_US` in provider `faker.providers.automotive`.
2025-08-29 09:15:28,655 - DEBUG - Provider `faker.providers.automotive` has been localized to `en_US`.
2025-08-29 09:15:28,657 - DEBUG - Looking for locale `en_US` in provider `faker.providers.bank`.
2025-08-29 09:15:28,660 - DEBUG - Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2025-08-29 09:15:28,660 - DEBUG - Looking for locale `en_US` in provider `faker.providers.barcode`.
2025-08-29 09:15:28,661 - DEBUG - Provider `faker.providers.barcode` has been localized to `en_US`.
2025-08-29 09:15:28,662 - DEBUG - Looking for locale `en_US` in provider `faker.providers.color`.
2025-08-29 09:15:28,664 - DEBUG - Provider `faker.providers.color` has been localized to `en_US`.
2025-08-29 09:15:28,665 - DEBUG - Looking for locale `en_US` in provider `faker.providers.company`.
2025-08-29 09:15:28,669 - DEBUG - Provider `faker.providers.company` has been localized to `en_US`.
2025-08-29 09:15:28,670 - DEBUG - Looking for locale `en_US` in provider `faker.providers.credit_card`.
2025-08-29 09:15:28,671 - DEBUG - Provider `faker.providers.credit_card` has been localized to `en_US`.
2025-08-29 09:15:28,672 - DEBUG - Looking for locale `en_US` in provider `faker.providers.currency`.
2025-08-29 09:15:28,675 - DEBUG - Provider `faker.providers.currency` has been localized to `en_US`.
2025-08-29 09:15:28,676 - DEBUG - Looking for locale `en_US` in provider `faker.providers.date_time`.
2025-08-29 09:15:28,680 - DEBUG - Provider `faker.providers.date_time` has been localized to `en_US`.
2025-08-29 09:15:28,681 - DEBUG - Provider `faker.providers.doi` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:15:28,681 - DEBUG - Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:15:28,681 - DEBUG - Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:15:28,682 - DEBUG - Looking for locale `en_US` in provider `faker.providers.geo`.
2025-08-29 09:15:28,682 - DEBUG - Provider `faker.providers.geo` has been localized to `en_US`.
2025-08-29 09:15:28,683 - DEBUG - Looking for locale `en_US` in provider `faker.providers.internet`.
2025-08-29 09:15:28,687 - DEBUG - Provider `faker.providers.internet` has been localized to `en_US`.
2025-08-29 09:15:28,688 - DEBUG - Looking for locale `en_US` in provider `faker.providers.isbn`.
2025-08-29 09:15:28,688 - DEBUG - Provider `faker.providers.isbn` has been localized to `en_US`.
2025-08-29 09:15:28,689 - DEBUG - Looking for locale `en_US` in provider `faker.providers.job`.
2025-08-29 09:15:28,692 - DEBUG - Provider `faker.providers.job` has been localized to `en_US`.
2025-08-29 09:15:28,693 - DEBUG - Looking for locale `en_US` in provider `faker.providers.lorem`.
2025-08-29 09:15:28,695 - DEBUG - Provider `faker.providers.lorem` has been localized to `en_US`.
2025-08-29 09:15:28,695 - DEBUG - Looking for locale `en_US` in provider `faker.providers.misc`.
2025-08-29 09:15:28,695 - DEBUG - Provider `faker.providers.misc` has been localized to `en_US`.
2025-08-29 09:15:28,696 - DEBUG - Looking for locale `en_US` in provider `faker.providers.passport`.
2025-08-29 09:15:28,697 - DEBUG - Provider `faker.providers.passport` has been localized to `en_US`.
2025-08-29 09:15:28,697 - DEBUG - Looking for locale `en_US` in provider `faker.providers.person`.
2025-08-29 09:15:28,703 - DEBUG - Provider `faker.providers.person` has been localized to `en_US`.
2025-08-29 09:15:28,705 - DEBUG - Looking for locale `en_US` in provider `faker.providers.phone_number`.
2025-08-29 09:15:28,710 - DEBUG - Provider `faker.providers.phone_number` has been localized to `en_US`.
2025-08-29 09:15:28,711 - DEBUG - Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:15:28,711 - DEBUG - Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:15:28,711 - DEBUG - Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:15:28,712 - DEBUG - Looking for locale `en_US` in provider `faker.providers.ssn`.
2025-08-29 09:15:28,715 - DEBUG - Provider `faker.providers.ssn` has been localized to `en_US`.
2025-08-29 09:15:28,716 - DEBUG - Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:15:29,351 - INFO - MainWindow.__init__ started.
2025-08-29 09:15:29,395 - INFO - MainWindow.__init__ finished.
2025-08-29 09:15:33,396 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2025-08-29 09:15:33,787 - ERROR - Error in worker thread for get_proxy_list: super(type, obj): obj (instance of SSLSocket) is not an instance or subtype of type (SSLSocket).
Traceback (most recent call last):
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\gui.py", line 377, in run_tool
    with contextlib.redirect_stdout(output_stream): self.func()
                                                    ~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\script\tools\proxy_fetcher.py", line 56, in get_proxy_list
    resp = session.get(url, timeout=20)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\adapters.py", line 644, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 969, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\util\ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\util\ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1012, in _create
    super(SSLSocket, self).__init__(**kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: super(type, obj): obj (instance of SSLSocket) is not an instance or subtype of type (SSLSocket).
