2025-08-29 09:07:54,550 - INFO - Application starting...
2025-08-29 09:07:54,883 - DEBUG - Starting new HTTPS connection (1): api.telegra.ph:443
2025-08-29 09:07:56,054 - DEBUG - https://api.telegra.ph:443 "POST /createAccount/ HTTP/1.1" 200 216
2025-08-29 09:07:57,053 - DEBUG - Not in REPL -> leaving logger event level as is.
2025-08-29 09:07:57,056 - DEBUG - Looking for locale `en_US` in provider `faker.providers.address`.
2025-08-29 09:07:57,061 - DEBUG - Provider `faker.providers.address` has been localized to `en_US`.
2025-08-29 09:07:57,063 - DEBUG - Looking for locale `en_US` in provider `faker.providers.automotive`.
2025-08-29 09:07:57,067 - DEBUG - Provider `faker.providers.automotive` has been localized to `en_US`.
2025-08-29 09:07:57,069 - DEBUG - Looking for locale `en_US` in provider `faker.providers.bank`.
2025-08-29 09:07:57,071 - DEBUG - Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2025-08-29 09:07:57,072 - DEBUG - Looking for locale `en_US` in provider `faker.providers.barcode`.
2025-08-29 09:07:57,072 - DEBUG - Provider `faker.providers.barcode` has been localized to `en_US`.
2025-08-29 09:07:57,074 - DEBUG - Looking for locale `en_US` in provider `faker.providers.color`.
2025-08-29 09:07:57,077 - DEBUG - Provider `faker.providers.color` has been localized to `en_US`.
2025-08-29 09:07:57,078 - DEBUG - Looking for locale `en_US` in provider `faker.providers.company`.
2025-08-29 09:07:57,081 - DEBUG - Provider `faker.providers.company` has been localized to `en_US`.
2025-08-29 09:07:57,082 - DEBUG - Looking for locale `en_US` in provider `faker.providers.credit_card`.
2025-08-29 09:07:57,083 - DEBUG - Provider `faker.providers.credit_card` has been localized to `en_US`.
2025-08-29 09:07:57,084 - DEBUG - Looking for locale `en_US` in provider `faker.providers.currency`.
2025-08-29 09:07:57,086 - DEBUG - Provider `faker.providers.currency` has been localized to `en_US`.
2025-08-29 09:07:57,087 - DEBUG - Looking for locale `en_US` in provider `faker.providers.date_time`.
2025-08-29 09:07:57,091 - DEBUG - Provider `faker.providers.date_time` has been localized to `en_US`.
2025-08-29 09:07:57,092 - DEBUG - Provider `faker.providers.doi` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:07:57,092 - DEBUG - Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:07:57,092 - DEBUG - Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:07:57,092 - DEBUG - Looking for locale `en_US` in provider `faker.providers.geo`.
2025-08-29 09:07:57,093 - DEBUG - Provider `faker.providers.geo` has been localized to `en_US`.
2025-08-29 09:07:57,094 - DEBUG - Looking for locale `en_US` in provider `faker.providers.internet`.
2025-08-29 09:07:57,097 - DEBUG - Provider `faker.providers.internet` has been localized to `en_US`.
2025-08-29 09:07:57,098 - DEBUG - Looking for locale `en_US` in provider `faker.providers.isbn`.
2025-08-29 09:07:57,099 - DEBUG - Provider `faker.providers.isbn` has been localized to `en_US`.
2025-08-29 09:07:57,100 - DEBUG - Looking for locale `en_US` in provider `faker.providers.job`.
2025-08-29 09:07:57,102 - DEBUG - Provider `faker.providers.job` has been localized to `en_US`.
2025-08-29 09:07:57,103 - DEBUG - Looking for locale `en_US` in provider `faker.providers.lorem`.
2025-08-29 09:07:57,106 - DEBUG - Provider `faker.providers.lorem` has been localized to `en_US`.
2025-08-29 09:07:57,106 - DEBUG - Looking for locale `en_US` in provider `faker.providers.misc`.
2025-08-29 09:07:57,107 - DEBUG - Provider `faker.providers.misc` has been localized to `en_US`.
2025-08-29 09:07:57,107 - DEBUG - Looking for locale `en_US` in provider `faker.providers.passport`.
2025-08-29 09:07:57,108 - DEBUG - Provider `faker.providers.passport` has been localized to `en_US`.
2025-08-29 09:07:57,109 - DEBUG - Looking for locale `en_US` in provider `faker.providers.person`.
2025-08-29 09:07:57,114 - DEBUG - Provider `faker.providers.person` has been localized to `en_US`.
2025-08-29 09:07:57,117 - DEBUG - Looking for locale `en_US` in provider `faker.providers.phone_number`.
2025-08-29 09:07:57,121 - DEBUG - Provider `faker.providers.phone_number` has been localized to `en_US`.
2025-08-29 09:07:57,122 - DEBUG - Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:07:57,123 - DEBUG - Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:07:57,123 - DEBUG - Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:07:57,123 - DEBUG - Looking for locale `en_US` in provider `faker.providers.ssn`.
2025-08-29 09:07:57,127 - DEBUG - Provider `faker.providers.ssn` has been localized to `en_US`.
2025-08-29 09:07:57,128 - DEBUG - Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:07:57,819 - INFO - MainWindow.__init__ started.
2025-08-29 09:07:57,872 - INFO - MainWindow.__init__ finished.
2025-08-29 09:08:01,083 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2025-08-29 09:08:01,274 - ERROR - Error in worker thread for get_proxy_list: maximum recursion depth exceeded
Traceback (most recent call last):
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\gui.py", line 377, in run_tool
    with contextlib.redirect_stdout(output_stream): self.func()
                                                    ~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\script\tools\proxy_fetcher.py", line 43, in get_proxy_list
    resp = session.get(url, timeout=20)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\adapters.py", line 644, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 922, in _ssl_wrap_socket_and_match_hostname
    context = create_urllib3_context(
        ssl_version=resolve_ssl_version(ssl_version),
    ...<2 lines>...
        cert_reqs=resolve_cert_reqs(cert_reqs),
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\util\ssl_.py", line 303, in create_urllib3_context
    context.minimum_version = TLSVersion.TLSv1_2
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 545, in minimum_version
    super(SSLContext, SSLContext).minimum_version.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 545, in minimum_version
    super(SSLContext, SSLContext).minimum_version.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 545, in minimum_version
    super(SSLContext, SSLContext).minimum_version.__set__(self, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  [Previous line repeated 984 more times]
RecursionError: maximum recursion depth exceeded
2025-08-29 09:08:03,623 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
