2025-08-29 09:22:35,199 - INFO - Application starting...
2025-08-29 09:22:35,539 - DEBUG - Starting new HTTPS connection (1): api.telegra.ph:443
2025-08-29 09:22:36,717 - DEBUG - https://api.telegra.ph:443 "POST /createAccount/ HTTP/1.1" 200 214
2025-08-29 09:22:37,727 - DEBUG - Not in REPL -> leaving logger event level as is.
2025-08-29 09:22:37,731 - DEBUG - Looking for locale `en_US` in provider `faker.providers.address`.
2025-08-29 09:22:37,735 - DEBUG - Provider `faker.providers.address` has been localized to `en_US`.
2025-08-29 09:22:37,738 - DEBUG - Looking for locale `en_US` in provider `faker.providers.automotive`.
2025-08-29 09:22:37,741 - DEBUG - Provider `faker.providers.automotive` has been localized to `en_US`.
2025-08-29 09:22:37,742 - DEBUG - Looking for locale `en_US` in provider `faker.providers.bank`.
2025-08-29 09:22:37,745 - DEBUG - Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2025-08-29 09:22:37,746 - DEBUG - Looking for locale `en_US` in provider `faker.providers.barcode`.
2025-08-29 09:22:37,748 - DEBUG - Provider `faker.providers.barcode` has been localized to `en_US`.
2025-08-29 09:22:37,749 - DEBUG - Looking for locale `en_US` in provider `faker.providers.color`.
2025-08-29 09:22:37,751 - DEBUG - Provider `faker.providers.color` has been localized to `en_US`.
2025-08-29 09:22:37,752 - DEBUG - Looking for locale `en_US` in provider `faker.providers.company`.
2025-08-29 09:22:37,755 - DEBUG - Provider `faker.providers.company` has been localized to `en_US`.
2025-08-29 09:22:37,756 - DEBUG - Looking for locale `en_US` in provider `faker.providers.credit_card`.
2025-08-29 09:22:37,758 - DEBUG - Provider `faker.providers.credit_card` has been localized to `en_US`.
2025-08-29 09:22:37,759 - DEBUG - Looking for locale `en_US` in provider `faker.providers.currency`.
2025-08-29 09:22:37,762 - DEBUG - Provider `faker.providers.currency` has been localized to `en_US`.
2025-08-29 09:22:37,763 - DEBUG - Looking for locale `en_US` in provider `faker.providers.date_time`.
2025-08-29 09:22:37,767 - DEBUG - Provider `faker.providers.date_time` has been localized to `en_US`.
2025-08-29 09:22:37,768 - DEBUG - Provider `faker.providers.doi` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:22:37,768 - DEBUG - Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:22:37,768 - DEBUG - Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:22:37,768 - DEBUG - Looking for locale `en_US` in provider `faker.providers.geo`.
2025-08-29 09:22:37,769 - DEBUG - Provider `faker.providers.geo` has been localized to `en_US`.
2025-08-29 09:22:37,770 - DEBUG - Looking for locale `en_US` in provider `faker.providers.internet`.
2025-08-29 09:22:37,773 - DEBUG - Provider `faker.providers.internet` has been localized to `en_US`.
2025-08-29 09:22:37,774 - DEBUG - Looking for locale `en_US` in provider `faker.providers.isbn`.
2025-08-29 09:22:37,775 - DEBUG - Provider `faker.providers.isbn` has been localized to `en_US`.
2025-08-29 09:22:37,776 - DEBUG - Looking for locale `en_US` in provider `faker.providers.job`.
2025-08-29 09:22:37,778 - DEBUG - Provider `faker.providers.job` has been localized to `en_US`.
2025-08-29 09:22:37,779 - DEBUG - Looking for locale `en_US` in provider `faker.providers.lorem`.
2025-08-29 09:22:37,782 - DEBUG - Provider `faker.providers.lorem` has been localized to `en_US`.
2025-08-29 09:22:37,782 - DEBUG - Looking for locale `en_US` in provider `faker.providers.misc`.
2025-08-29 09:22:37,783 - DEBUG - Provider `faker.providers.misc` has been localized to `en_US`.
2025-08-29 09:22:37,784 - DEBUG - Looking for locale `en_US` in provider `faker.providers.passport`.
2025-08-29 09:22:37,784 - DEBUG - Provider `faker.providers.passport` has been localized to `en_US`.
2025-08-29 09:22:37,785 - DEBUG - Looking for locale `en_US` in provider `faker.providers.person`.
2025-08-29 09:22:37,791 - DEBUG - Provider `faker.providers.person` has been localized to `en_US`.
2025-08-29 09:22:37,793 - DEBUG - Looking for locale `en_US` in provider `faker.providers.phone_number`.
2025-08-29 09:22:37,798 - DEBUG - Provider `faker.providers.phone_number` has been localized to `en_US`.
2025-08-29 09:22:37,799 - DEBUG - Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:22:37,799 - DEBUG - Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:22:37,800 - DEBUG - Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:22:37,800 - DEBUG - Looking for locale `en_US` in provider `faker.providers.ssn`.
2025-08-29 09:22:37,804 - DEBUG - Provider `faker.providers.ssn` has been localized to `en_US`.
2025-08-29 09:22:37,805 - DEBUG - Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2025-08-29 09:22:38,462 - INFO - MainWindow.__init__ started.
2025-08-29 09:22:38,504 - INFO - MainWindow.__init__ finished.
2025-08-29 09:22:42,568 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2025-08-29 09:22:42,755 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2025-08-29 09:22:43,164 - ERROR - Error in worker thread for get_proxy_list: super(type, obj): obj (instance of SSLSocket) is not an instance or subtype of type (SSLSocket).
Traceback (most recent call last):
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\gui.py", line 377, in run_tool
    with contextlib.redirect_stdout(output_stream): self.func()
                                                    ~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\script\tools\proxy_fetcher.py", line 78, in get_proxy_list
    resp = session.get(url, timeout=20)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\requests\adapters.py", line 644, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\connection.py", line 969, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\util\ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\ShShu\Downloads\search-feature-gui-replacement\laitoxx\env\Lib\site-packages\urllib3\util\ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ShShu\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1012, in _create
    super(SSLSocket, self).__init__(**kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: super(type, obj): obj (instance of SSLSocket) is not an instance or subtype of type (SSLSocket).
